apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-ghost-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-ghost
  template:
    metadata:
      labels:
        app: blog-ghost
    spec:
      containers:
      - name: ghost
        image: ghost:1-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: ghostport
          containerPort: 2368
        env:
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: blog-db-svc
        - name: database__connection__port
          value: "8888"
        - name: database__connection__user
          value: root
        - name: database__connection__password
          value: welcome
        - name: database__connection__database
          value: ghost

---

apiVersion: v1
kind: Service
metadata:
  name: blog-ghost-svc
spec:
  ports:
  - port: 8888
    targetPort: ghostport
    nodePort: 32001
    protocol: TCP
  #Selector helps to identify the ipaddresses of the pods to which this service has to load balance  
  selector:
    app: blog-ghost
  type: NodePort
