apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sayhiregularly
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hi
            image: alpine
            command: ["echo", "Hello there"]
          restartPolicy: OnFailure
